### ISSUE TITLE
Diseño arquitectónico

### ISSUE THREAD

**Issue by Adripy** [jesgararm/go-bees#14]

**Comment by jesgararm** [comment]
davidmigloz added a commit that referenced this issue on 23 Jan 2017
@davidmigloz
Document Diseno Arquitectonico #150

davidmigloz added a commit that referenced this issue on 23 Jan 2017
@davidmigloz
Add references #150

davidmigloz added a commit that referenced this issue on 24 Jan 2017
@davidmigloz
Improve Diseno Arquitectonico documentation #150
