### ISSUE TITLE
Pasar memoria doc a latex

### ISSUE THREAD

**Issue by jesgararm** [jesgararm/go-bees#19]
- Revisar imágenes.
- Revisar bibliografía.
- bibentry (http://gking.harvard.edu/files/bibentry2.pdf).

**Documentación** 
- Resumen
- Introducción
- Objetivos del proyecto
- Conceptos teóricos
- Técnicas y herramientas
- Aspectos relevantes
- Trabajos relacionados
- Conclusiones y Líneas de trabajo futuras

**Comment by Adripy** [comment]
Expresión regular para corregir las referencias:

- Buscar: `(\{\[\})([\w:\\]+)(\{\]\}\\\_)`

- Reemplazar por:` \\citep{\2}`

Ej: `{[}art:campbell2005{]}\_` -> `\citep{art:campbell2005}`
### 
Expresión regular para corregir las imágenes:

- Buscar:` (\\includegraphics{..\/..\/img\/)(\w*)(.\w*\})`

- Reemplazar por: `\\imagen{\2}{descripción...}`

Ej: `\includegraphics{../../img/s2.png}` -> `\imagen{s2}{descripción...}}`

**Comment by Adripy** [comment]
### Cheat-sheet plantilla
**Rutas de ficheros / paquetes**
`\ruta{C:/Windows/System32}`
**Imágenes**
Imagen en el sitio introducido:

`\imagen{nombre-img}{Descripción...}`
Imagen flotante:

`\imagenflotante{nombre-img}{Descripción...}`
El nombre de la imagen sin extensión.

**Comment by Adripy** [comment]
davidmigloz added a commit that referenced this issue on 25 Jan 2017
@davidmigloz
Convert to latex points 1 and 2 #124

davidmigloz added a commit that referenced this issue on 26 Jan 2017
@davidmigloz
Convert to latex point 3 #124

**Comment by Adripy** [comment]
davidmigloz added a commit that referenced this issue on 27 Jan 2017
@davidmigloz
Convert to latex point 4 #124

davidmigloz added a commit that referenced this issue on 28 Jan 2017
@davidmigloz
Convert to latex point 5 #124

davidmigloz added a commit that referenced this issue on 28 Jan 2017
@davidmigloz
Convert to latex point 6 #124

@davidmigloz davidmigloz changed the estimate from 8 to 13 on 28 Jan 2017
davidmigloz added a commit that referenced this issue on 28 Jan 2017
@davidmigloz
Convert to latex point 7 #124
