### ISSUE TITLE
Resources$NotFoundException con vectores en Android < 21

### ISSUE THREAD

**Issue by jesgararm** [jesgararm/go-bees#21]
https://medium.com/@chrisbanes/appcompat-v23-2-age-of-the-vectors-91cbafa87c88#.u93ttzjpb

**Comment by Adripy** [comment]
![image](https://user-images.githubusercontent.com/36918572/142934446-f4d38e86-9d72-4c84-813a-dd6d3583f307.png)
https://medium.com/@ferrand.d/can-you-and-should-you-use-vector-drawables-a-cheatsheet-32a2e1cc2ecf#.eoek6mlry

**Comment by Adripy** [comment]
davidmigloz added a commit that referenced this issue on 29 Jan 2017
@davidmigloz
Fix exception with vectors in API < 21 #181
