### ISSUE TITLE
Publicar en Google Play

### ISSUE THREAD

**Issue by jesgararm** [jesgararm/go-bees#25]
https://support.google.com/googleplay/android-developer/answer/113469#privacy

https://www.raywenderlich.com/122114/android-app-distribution-tutorial-zero-google-play-store

**Comment by Adripy** [comment]
![image](https://user-images.githubusercontent.com/36918572/142935401-dbd13e0a-4088-4172-83ab-dfc671a78130.png)![image](https://user-images.githubusercontent.com/36918572/142935462-e467e888-8d82-4682-b428-4c5f8f8a840c.png)![image](https://user-images.githubusercontent.com/36918572/142935414-8fa33f45-99ea-4be6-a45f-bcec6d4400c5.png)
![image](https://user-images.githubusercontent.com/36918572/142935427-55f70eb4-0a1a-474a-8d08-35b568f2ad8f.png)
![image](https://user-images.githubusercontent.com/36918572/142935439-7f59bd44-d991-49d9-8497-d3daca0282c8.png)
![image](https://user-images.githubusercontent.com/36918572/142935462-e467e888-8d82-4682-b428-4c5f8f8a840c.png)
![image](https://user-images.githubusercontent.com/36918572/142935474-235004a2-4c73-4409-96ff-6ba896c36ddd.png)

**Comment by Adripy** [comment]
https://play.google.com/store/apps/details?id=com.davidmiguel.gobees
