### ISSUE TITLE
Manual del programador

### ISSUE THREAD

**Issue by Adripy** [jesgararm/go-bees#32]
- Instalación Android Studio
- Importación del proyecto
- Estructura directorios
- Ejecución tests en local
- Servicios de integración continua
- Creación de un ejecutable
- Plataforma de desarrollo del algoritmo
- Plataforma de conteo

**Comment by jesgararm** [comment]
davidmigloz added a commit that referenced this issue on 3 Feb 2017
@davidmigloz
Add javadoc #151 

davidmigloz added a commit that referenced this issue on 5 Feb 2017
@davidmigloz
Document Manual Programador #151
