### ISSUE TITLE
Grabar discos

### ISSUE THREAD

**Issue by jesgararm** [jesgararm/go-bees#34]
-  Código fuente app
-  Ejecutable app
-  Herramientas
  -  Plataforma de desarrollo del algoritmo
  -  Herramienta de conteo de abejas
- Documentación
  - Memoria
  -  Anexos
  - JavaDoc
- Dataset de videos

**README**

-  Repositorio GoBees
-  Repositorio prototipos
-  Repositorio dependencia OpenCV

**Comment by Adripy** [comment]
davidmigloz added a commit that referenced this issue on 1 Feb 2017
@davidmigloz
Add cd cover #173

davidmigloz added a commit that referenced this issue on 1 Feb 2017
@davidmigloz
Add cd cover #173
