### ISSUE TITLE
Diseñar poster 

### ISSUE THREAD

**Issue by jesgararm** [jesgararm/go-bees#37]

**Comment by Adripy** [comment]
davidmigloz added a commit that referenced this issue on 14 Feb 2017
@davidmigloz
Add poster #157

**Comment by Adripy** [comment]
https://raw.githubusercontent.com/davidmigloz/go-bees/master/docs/latex/cartel.jpg

**Comment by Adripy** [comment]
davidmigloz added a commit that referenced this issue on 16 Feb 2017
@davidmigloz
Update poster #157
