### ISSUE TITLE
Integración de SonarQube

### ISSUE THREAD

**Issue by Adripy** [jesgararm/go-bees#4]
Aunque ya se cuenta con code climate y codecov entre los servicios de integración continua para evaluar la calidad del código, sería recomendable pasar también los motores de análisis de SonarQube ya que es el que utilizará el tribunal para evaluar el TFG.

https://sonarqube.com/
https://github.com/integrations/sonarqube
https://docs.travis-ci.com/user/sonarqube/

**Comment by jesgararm** [comment]
davidmigloz added a commit that referenced this issue on 18 Jan 2017
@davidmigloz
Integrate SonarQube #155

**Comment by jesgararm** [comment]
davidmigloz added a commit that referenced this issue on 18 Jan 2017
@davidmigloz
Minor fix SonarQube #155 
 Minor fixes #155 
@davidmigloz
Minor fixes #155 

@davidmigloz
Finish SonarQube integration #155
