### ISSUE TITLE
Mejorar vistas para tablets

### ISSUE THREAD

**Issue by Adripy** [jesgararm/go-bees#46]
### Mejoras tablet

- [x] redimensionar fuentes
- [x] redimensionado de imagenes
- [x] recolocar menu
- [x] recolocar logo
- [x] comprobar scroll
- [x] redimensionar API maps

**Comment by Adripy** [comment]
Adripy added a commit that referenced this issue on 30 Dic 2021
@Adripy
Logo, maps, main #XX

**Comment by Adripy** [comment]
Adripy added a commit that referenced this issue on 31 Dic 2021
@Adripy
Scroll #XX

**Comment by jesgararm** [comment]
jesgararm added a commit that referenced this issue on 31 Dic 2021
@jesgararm  
Img and font resize #XX
