### ISSUE TITLE
Las imágenes no se posicionan correctamente en el pdf autogenerado

### ISSUE THREAD

**Issue by Adripy** [jesgararm/go-bees#7]

**Comment by jesgararm** [comment]
http://stackoverflow.com/questions/24285445/sphinx-to-latex-figure-placement

**Comment by jesgararm** [comment]
davidmigloz added a commit that referenced this issue on 20 Jan 2017
@davidmigloz
Fix pdf images position #164 
davidmigloz added a commit that referenced this issue on 20 Jan 2017
@davidmigloz
Fix images position #164
271284b
davidmigloz added a commit that referenced this issue on 20 Jan 2017
@davidmigloz
Fix images position #164
844ae52
davidmigloz added a commit that referenced this issue on 20 Jan 2017
@davidmigloz
Fix images position #164
5255bc8
davidmigloz added a commit that referenced this issue on 20 Jan 2017
@davidmigloz
Fix images position #164
683e2a4
davidmigloz added a commit that referenced this issue on 21 Jan 2017
@davidmigloz
Fix images position #164
42db24a
davidmigloz added a commit that referenced this issue on 21 Jan 2017
@davidmigloz
Fix images position #164
5209017
davidmigloz added a commit that referenced this issue on 21 Jan 2017
@davidmigloz
Fix images position #164
